apiVersion: v1
kind: ReplicationController
metadata:
  name: website-rc
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: website
      labels:
        app: frontend
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: website-pvc
      containers:
      - name: webserver
        image: php:7.3-apache
        ports:
        - name: http 
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/html"
          name: data
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "website-prod"
    ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: kubernetes.groovesoundz.be
    http:
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 80
  tls:
  - hosts:
    - kubernetes.groovesoundz.be
    secretName: website-prod
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: website-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: christof@groovesoundz.be
    privateKeySecretRef:
      name: website-prod
    solvers:
    - http01:
       ingress:
         class: nginx